### ISSUE TITLE
.bind() in spooky.js breaking tiny-jsonrpc 

### ISSUE THREAD

**Issue by NateV** [SpookyJS/SpookyJS#181] opened 2015-12-13 20:28 UTC
Hi, 
With: 
-mac with OS 10.10.5, 
-node v4.0.0,
-casperjs v1.0.4
-phantomjs v2.0.0
-spooky v0.2.5

spooky.js around line 150 creates an object containing a function with .bind() as follows
```
     { emit: function() {
          this.emit.apply(this, arguments);
          return true;
          }.bind(this)}
```
spooky.js then sends the object to `_rpcServer.provide(obj)`.  The tiny-jsonrpc method `Server.prototyp._provide` in server.js has to parse the function from spooky.js by converting the function to a string with `toString()` and pulling out the function's name and arguments from the string.  Line 67:
```
var parsed = fn.toString().match(/function\s+(\w+)?\((.*)\)/);
```

When server.js is trying to parse the `emit` function from spooky.js, it cannot, because spooky, by calling `.bind()` on the function, has turned the function into a bound function with native code. Parsing the function with `toString()` no longer works. 

If I've just set something up wrong, I apologize, but I can't figure out a way around the problem of spooky sending a bound function with native code to a function that needs to parse the function as a string.

**Comment by lawnsea** [comment] 2016-02-25 06:02
Turns out this a dupe of #172

**Closed by lawnsea** 2016-02-25 06:02 UTC
Labels: duplicate
