### ISSUE TITLE
Odd behavior with accented characters

### ISSUE THREAD

**Issue by mtlmtlmtl** [SpookyJS/SpookyJS#142] opened 2015-04-23 03:05 UTC
I'm having problems with accented characters. For example, if I put `console.log('é');`in the hello.js example right before the `var spooky = new Spooky` on line 7, it works fine but if I put it inside a `spooky.then(function () {` on line 24, it just hangs after starting. I've tried many different things to try to have it use the accented characters but it always hangs (it just displays `[info] [phantom] Starting...`).
It works fine on my local machine (MacOSX) but it has problems on my Centos server. Any pointers would be greatly appreciated. Thanks.

**Comment by lawnsea** [comment] 2015-04-23 17:06
This is probably a duplicate of #110. It's fixed in 3235388.

**Closed by lawnsea** 2015-04-23 17:06 UTC

**Comment by mtlmtlmtl** [comment] 2015-04-23 17:09
Sorry, didn't see that one! I thought I searched everything. Thanks!
